In [115]:
import numpy
import torch

def Convolution2D(in_tensor, weight, kernel_size, stride=1, padding=0, dilation=1, bias=True):
    if isinstance(padding, int):
        padding = (padding, padding)
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size, kernel_size)
    if isinstance(stride, int):
        stride = (stride, stride)
    if isinstance(dilation, int):
        dilation = (dilation, dilation)
    
    in_channels, in_height, in_width = in_tensor.shape
    out_channels = weight.shape[0]

    if padding[0] > 0 and padding[1] > 0:
        in_tensor = torch.nn.functional.pad(in_tensor, (padding[0], padding[1], padding[0], padding[1]), mode='constant')
    
    out_height = (in_height - dilation[0] * (kernel_size[0] - 1) + 2 * padding[0] - 1) // stride[0] + 1
    out_width = (in_width - dilation[1] * (kernel_size[1] - 1) + 2 * padding[1] - 1) // stride[1] + 1
    out_tensor = numpy.zeros((out_channels, out_height, out_width))

    for c in range(out_channels):
        for h in range(0, in_height - kernel_size[0] + 1, stride[0]):
            for w in range(0, in_width - kernel_size[1] + 1, stride[1]):
                conv = in_tensor[:, h:h+kernel_size[0], w:w+kernel_size[1]]
                out_tensor[c, h//stride[0], w//stride[1]] = (conv * weight[c]).sum() 
    
    if bias:
        bias_ = numpy.random.randn(out_channels)
        out_tensor += bias_.reshape(-1, 1, 1)
    
    return out_tensor

In [126]:
def test1():
    input_ = torch.randn(1, 256, 256)
    weight_ = torch.randn(1, 4, 4)
    res = Convolution2D(input_, weight_, kernel_size=weight_.shape[1])
    print('Размер тензора -', res.shape)
    return res

In [127]:
def test2():
    input_ = torch.randn(1, 256, 256)
    weight_ = torch.randn(1, 4, 4)
    res = Convolution2D(input_, weight_, kernel_size=weight_.shape[1], padding=1)
    print('Размер тензора -', res.shape)
    return res

In [128]:
def test3():
    input_ = torch.randn(1, 256, 256)
    weight_ = torch.randn(1, 4, 4)
    res = Convolution2D(input_, weight_, kernel_size=weight_.shape[1], stride=2)
    print('Размер тензора -', res.shape)
    return res

In [129]:
test1()

Размер тензора - (1, 253, 253)


array([[[-0.66569452, -3.56079583,  0.83084578, ..., -4.0849443 ,
         -0.10503714,  1.97574467],
        [-1.4915206 , -2.82763868, -0.39733701, ...,  2.06292243,
         -1.45518809, -0.0931543 ],
        [-4.27777677, -4.48135023,  1.27285118, ..., -3.19855814,
         -5.03275686,  4.25817675],
        ...,
        [ 4.27295251, -2.93570595,  1.67964549, ..., -2.90940314,
         -3.84995346, -3.51467281],
        [-0.48494225, -2.26488488,  2.28206963, ...,  1.64808316,
         -4.80999093, -5.26820808],
        [-7.34784417,  1.26062436,  1.2945661 , ..., -0.15839105,
          0.8278007 , -2.97556119]]])

In [130]:
test2()

Размер тензора - (1, 255, 255)


array([[[ 2.93439618,  5.28888264, -0.13080415, ...,  9.04563465,
         -0.65459594, -0.65459594],
        [-3.40719709,  3.02514711,  0.47978177, ..., -1.42887512,
         -0.65459594, -0.65459594],
        [-0.06385002, -3.23415098,  5.91963044, ..., -2.00739286,
         -0.65459594, -0.65459594],
        ...,
        [ 0.12802139,  2.34044185, -0.55005467, ..., -2.33199844,
         -0.65459594, -0.65459594],
        [-0.65459594, -0.65459594, -0.65459594, ..., -0.65459594,
         -0.65459594, -0.65459594],
        [-0.65459594, -0.65459594, -0.65459594, ..., -0.65459594,
         -0.65459594, -0.65459594]]])

In [131]:
test3()

Размер тензора - (1, 127, 127)


array([[[ 2.55642194, -2.87684506, -0.66542929, ...,  4.12605554,
          0.53154516,  4.00986678],
        [ 4.70837718, -3.63988131,  2.71175653, ..., -3.54394263,
         -4.31177109, -6.10987872],
        [ 0.17656785,  2.97302932, -5.0690524 , ...,  3.71862322,
         -1.27087587,  2.15523362],
        ...,
        [ 0.05310029,  2.57496101, -0.76147598, ...,  5.7806533 ,
          7.97187263, -2.18663972],
        [ 4.76460678, 11.48067314,  3.90308029, ...,  5.06186563,
          4.12039   ,  1.16003579],
        [-8.30894822,  3.2656923 , -1.04336518, ..., -2.03598612,
          2.48091132, -3.14436644]]])

In [110]:
import numpy
import torch

def Convolution3D(in_tensor, weight, kernel_size, stride=1, padding=0, dilation=1, bias=True):
    if isinstance(padding, int):
        padding = (padding, padding, padding)
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size, kernel_size, kernel_size)
    if isinstance(stride, int):
        stride = (stride, stride, stride)
    if isinstance(dilation, int):
        dilation = (dilation, dilation, dilation)

    in_channels, in_depth, in_height, in_width = in_tensor.shape
    out_channels = weight.shape[0]
    
    if padding[0] > 0 and padding[1] > 0 and padding[2] > 0:
        in_tensor = torch.nn.functional.pad(in_tensor, (padding[0], padding[1], padding[2], padding[0], padding[1], padding[2]), mode='constant')

    out_depth = (in_depth - dilation[0] * (kernel_size[0] - 1) + 2 * padding[0] - 1) // stride[0] + 1
    out_height = (in_height - dilation[1] * (kernel_size[1] - 1) + 2 * padding[1] - 1) // stride[1] + 1
    out_width = (in_width - dilation[2] * (kernel_size[2] - 1) + 2 * padding[2] - 1) // stride[2] + 1
    out_tensor = numpy.zeros((out_channels, out_depth, out_height, out_width))

    for c in range(out_channels):
        for d in range(0, in_depth - kernel_size[0] + 1, stride[0]):
            for h in range(0, in_height - kernel_size[1] + 1, stride[1]):
                for w in range(0, in_width - kernel_size[2] + 1, stride[2]):
                    conv = in_tensor[:, d:d+kernel_size[0], h:h+kernel_size[1], w:w+kernel_size[2]]
                    out_tensor[c, d//stride[0], h//stride[1], w//stride[2]] = (conv * weight[c]).sum() 
    
    if bias:
        bias_ = numpy.random.randn(out_channels)
        out_tensor += bias_.reshape(-1, 1, 1, 1)
    
    return out_tensor

In [134]:
def test1_3d():
    input_ = torch.randn(4, 64, 64, 64)
    weight_ = torch.randn(1, 4, 4, 4)
    res = Convolution3D(input_, weight_, kernel_size=weight_.shape[1])
    print('Размер тензора -', res.shape)
    return res

In [136]:
def test2_3d():
    input_ = torch.randn(4, 64, 64, 64)
    weight_ = torch.randn(1, 4, 4, 4)
    res = Convolution3D(input_, weight_, kernel_size=weight_.shape[1], padding=2)
    print('Размер тензора -', res.shape)
    return res

In [139]:
def test3_3d():
    input_ = torch.randn(4, 64, 64, 64)
    weight_ = torch.randn(1, 4, 4, 4)
    res = Convolution3D(input_, weight_, kernel_size=weight_.shape[1], stride=2)
    print('Размер тензора -', res.shape)
    return res

In [135]:
test1_3d()

Размер тензора - (1, 61, 61, 61)


array([[[[-24.81572356,   8.54919419, -19.98117843, ...,   4.92983899,
          -20.13094916,   5.72010884],
         [-11.27807345,   7.38568864,  10.99780259, ...,  10.16809068,
           -7.05220952,   0.9630507 ],
         [ 16.01625428,   0.58934102,   5.25740419, ...,   5.26128945,
            2.31365905,   9.8959168 ],
         ...,
         [ 18.41593537,  23.83895478,  -9.45031753, ...,  23.66707025,
           -3.3512918 ,  -2.66451325],
         [  6.62738547, -14.03443351,  18.2248076 , ...,   2.35322437,
           14.13306031, -25.25737014],
         [ 41.98848519,  11.00853906,  -7.4992353 , ...,  16.09776673,
           -2.44372382,  10.60968385]],

        [[-19.87684455,   7.59178243, -14.08084502, ..., -17.50807967,
            6.65163455,  28.00967012],
         [  8.60436235,  19.23031983,   0.6423944 , ..., -14.06679549,
           20.02896867,  -5.91944232],
         [ -1.24242797,  -5.20428386,  -8.09734502, ..., -17.58900657,
          -26.05215278,  -5.55361

In [138]:
test2_3d()

Размер тензора - (1, 65, 65, 65)


array([[[[  7.58904351,   0.69500221,   0.47513105, ...,   0.32053031,
            0.32053031,   0.32053031],
         [  1.52205731,   6.63693275, -14.95617829, ...,   0.32053031,
            0.32053031,   0.32053031],
         [  4.67619266,   4.67917336,   3.96330298, ...,   0.32053031,
            0.32053031,   0.32053031],
         ...,
         [  0.32053031,   0.32053031,   0.32053031, ...,   0.32053031,
            0.32053031,   0.32053031],
         [  0.32053031,   0.32053031,   0.32053031, ...,   0.32053031,
            0.32053031,   0.32053031],
         [  0.32053031,   0.32053031,   0.32053031, ...,   0.32053031,
            0.32053031,   0.32053031]],

        [[ -6.65457498,  -4.27572213,   6.59294642, ...,   0.32053031,
            0.32053031,   0.32053031],
         [ -4.30975877, -10.66894971,  20.78262939, ...,   0.32053031,
            0.32053031,   0.32053031],
         [ 20.24235381,   8.56372108,  16.53666724, ...,   0.32053031,
            0.32053031,   0.32053

In [141]:
test3_3d()

Размер тензора - (1, 31, 31, 31)


array([[[[ 18.63489186,   9.83143174,   1.26680648, ...,  28.85647046,
          -23.08339656,  -9.12018169],
         [-13.32686675, -12.81786597,  19.01617848, ..., -12.95595897,
           11.86402165,  15.85387742],
         [  5.22274815,  -2.91457046,  -4.5793773 , ...,   2.28413331,
          -24.32930339,  11.74455582],
         ...,
         [ -5.51556218, -27.84227908, -16.75427211, ..., -28.47532428,
            8.88146865,  -3.58364213],
         [ 13.06921422,  -4.70273364,  13.48344456, ...,  -3.66802943,
           -1.78573955, -26.84297717],
         [ 25.96262776,  -3.58036864,  -4.54985583, ...,  16.0839523 ,
          -16.3221432 , -26.75461162]],

        [[  9.69337498, -12.88287414,   8.12080657, ...,   8.19262635,
           -3.08469642, -11.05334056],
         [  4.21865427,   5.32366788, -22.99239505, ...,   5.33198535,
          -14.06304992,  30.87460553],
         [ -4.77070392,  16.51045548, -13.84829391, ...,  -4.85840047,
           -6.58433212,  12.75618

In [186]:
def ConvTranspose(in_tensor, weight, kernel_size, stride=1, padding=0, dilation=1, output_padding=0, bias=True):
    if isinstance(padding, int):
        padding = (padding, padding)
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size, kernel_size)
    if isinstance(stride, int):
        stride = (stride, stride)
    if isinstance(dilation, int):
        dilation = (dilation, dilation)
    if isinstance(output_padding, int):
        output_padding = (output_padding, output_padding)

    in_channels, in_height, in_width = in_tensor.shape
    out_channels = weight.shape[0]

    if padding[0] > 0 and padding[1] > 0:
        in_tensor = torch.nn.functional.pad(in_tensor, (padding[0], padding[1], padding[0], padding[1]), mode='constant')
    
    out_height = (in_height - 1) * stride[0] - 2 * padding[0] + dilation[0] * (kernel_size[0] - 1) + 1 + output_padding[0]
    out_width = (in_width - 1) * stride[1] - 2 * padding[1] + dilation[1] * (kernel_size[1] - 1) + 1 + output_padding[1]
    out_tensor = numpy.zeros((out_channels, out_height, out_width))

    for h in range(in_height):
        for w in range(in_width):
            for i in range(kernel_size[0]):
                for j in range(kernel_size[1]):
                    for c in range(out_channels):
                        cur_h = h * stride[0] + i - padding[0]
                        cur_w = w * stride[1] + j - padding[1]
                        if 0 <= cur_h < in_height and 0 <= cur_w < in_width:
                            out_tensor[c, h, w] = in_tensor[c, cur_h, cur_w] * weight[c, i, j]
    return out_tensor

In [187]:
def test1_transpose():
    input_ = torch.randn(4, 64, 64)
    weight_ = torch.randn(2, 4, 4)
    res = ConvTranspose(input_, weight_, kernel_size=weight_.shape[1])
    print('Размер тензора -', res.shape)
    return res

In [188]:
def test2_transpose():
    input_ = torch.randn(4, 64, 64)
    weight_ = torch.randn(2, 4, 4)
    res = ConvTranspose(input_, weight_, kernel_size=weight_.shape[1], stride=2)
    print('Размер тензора -', res.shape)
    return res

In [189]:
def test3_transpose():
    input_ = torch.randn(4, 64, 64)
    weight_ = torch.randn(2, 4, 4)
    res = ConvTranspose(input_, weight_, kernel_size=weight_.shape[1], padding=1)
    print('Размер тензора -', res.shape)
    return res

In [190]:
test1_transpose()

Размер тензора - (2, 67, 67)


array([[[ 1.57871783, -0.82212144,  1.60805714, ...,  0.        ,
          0.        ,  0.        ],
        [-2.31243277,  0.78281897, -4.65421391, ...,  0.        ,
          0.        ,  0.        ],
        [-5.19114113, -3.37625647,  1.66517103, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[-1.69973755,  0.28928119,  0.33462399, ...,  0.        ,
          0.        ,  0.        ],
        [ 1.04366493,  0.29640558, -1.07164836, ...,  0.        ,
          0.        ,  0.        ],
        [-0.01404152,  0.47793847, -0.38175058, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  

In [191]:
test2_transpose()

Размер тензора - (2, 130, 130)


array([[[ 3.33396375e-01, -5.77821676e-03, -4.11380380e-01, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-2.93086981e-04,  1.47833362e-01, -1.13332741e-01, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.36053994e-01,  2.25824341e-01, -4.62218598e-02, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 2.78443307e-01,  6.50639176e-01,  4.46883589e-01, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-5.72866499e-01,  2.94897556e-01, -3.43649864e-01, ...,
          0.00000000e+00,  0.00000000e

In [192]:
test3_transpose()

Размер тензора - (2, 65, 65)


array([[[-1.77604651e+00, -3.58496271e-02,  1.09467483e+00, ...,
          1.19782519e+00,  5.20633459e-01,  0.00000000e+00],
        [ 1.31105280e+00, -8.29596877e-01,  1.73272383e+00, ...,
          1.33536112e+00,  5.80413342e-01,  0.00000000e+00],
        [ 1.32609367e+00,  9.81264412e-01, -1.24230182e+00, ...,
          2.40405273e+00,  1.04491901e+00,  0.00000000e+00],
        ...,
        [ 1.05429840e+00,  3.18155974e-01,  1.52175355e+00, ...,
         -6.96328841e-03,  2.18563721e-01,  0.00000000e+00],
        [-6.25571728e-01, -1.88778996e-01, -9.02937889e-01, ...,
         -1.14687635e-02,  4.03539315e-02,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],

       [[ 1.87963748e+00,  2.41471219e+00,  2.68705869e+00, ...,
          7.45853782e-02, -6.56260133e-01,  0.00000000e+00],
        [-5.83434045e-01,  3.89148045e+00,  7.45027810e-02, ...,
          2.41418462e-02, -2.12418720e

In [193]:
def ConvTranspose_alt(in_tensor, weight, kernel_size, stride=1, padding=0, dilation=1, output_padding=0, bias=True):
    if isinstance(padding, int):
        padding = (padding, padding)
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size, kernel_size)
    if isinstance(stride, int):
        stride = (stride, stride)
    if isinstance(dilation, int):
        dilation = (dilation, dilation)
    if isinstance(output_padding, int):
        output_padding = (output_padding, output_padding)

    in_channels, in_height, in_width = in_tensor.shape
    out_channels = weight.shape[0]

    if padding[0] > 0 and padding[1] > 0:
        in_tensor = torch.nn.functional.pad(in_tensor, (padding[0], padding[1], padding[0], padding[1]), mode='constant')
    
    out_height = (in_height - 1) * stride[0] - 2 * padding[0] + dilation[0] * (kernel_size[0] - 1) + 1 + output_padding[0]
    out_width = (in_width - 1) * stride[1] - 2 * padding[1] + dilation[1] * (kernel_size[1] - 1) + 1 + output_padding[1]
    out_tensor = numpy.zeros((out_channels, out_height, out_width))

    for c in range(out_channels):
        for h in range(in_height):
            for w in range(in_width):
                out_tensor[c, h * stride[0], w * stride[1]] = (in_tensor[:, h, w] * weight[c]).sum()
    
    if bias:
        bias_ = numpy.random.randn(out_channels)
        out_tensor += bias_.reshape(-1, 1, 1)

    return out_tensor

In [195]:
def test1_transpose_alt():
    input_ = torch.randn(1, 64, 64)
    weight_ = torch.randn(1, 4, 4)
    res = ConvTranspose_alt(input_, weight_, kernel_size=weight_.shape[1])
    print('Размер тензора -', res.shape)
    return res

In [196]:
def test2_transpose_alt():
    input_ = torch.randn(1, 64, 64)
    weight_ = torch.randn(1, 4, 4)
    res = ConvTranspose_alt(input_, weight_, kernel_size=weight_.shape[1], stride=2)
    print('Размер тензора -', res.shape)
    return res

In [197]:
def test3_transpose_alt():
    input_ = torch.randn(1, 64, 64)
    weight_ = torch.randn(1, 4, 4)
    res = ConvTranspose_alt(input_, weight_, kernel_size=weight_.shape[1], padding=1)
    print('Размер тензора -', res.shape)
    return res

In [198]:
def test4_transpose_alt():
    input_ = torch.randn(1, 64, 64)
    weight_ = torch.randn(1, 4, 4)
    res = ConvTranspose_alt(input_, weight_, kernel_size=weight_.shape[1], output_padding=1)
    print('Размер тензора -', res.shape)
    return res

In [199]:
test1_transpose_alt()

Размер тензора - (1, 67, 67)


array([[[ 2.32313609, -7.61665272, -2.46785426, ..., -0.41348195,
         -0.41348195, -0.41348195],
        [ 1.73601365, -0.79171481, -1.2120614 , ..., -0.41348195,
         -0.41348195, -0.41348195],
        [-0.9305917 ,  5.25441289, -3.27401757, ..., -0.41348195,
         -0.41348195, -0.41348195],
        ...,
        [-0.41348195, -0.41348195, -0.41348195, ..., -0.41348195,
         -0.41348195, -0.41348195],
        [-0.41348195, -0.41348195, -0.41348195, ..., -0.41348195,
         -0.41348195, -0.41348195],
        [-0.41348195, -0.41348195, -0.41348195, ..., -0.41348195,
         -0.41348195, -0.41348195]]])

In [200]:
test2_transpose_alt()

Размер тензора - (1, 130, 130)


array([[[0.2350228 , 1.36374607, 1.24613125, ..., 1.36374607,
         1.36374607, 1.36374607],
        [1.36374607, 1.36374607, 1.36374607, ..., 1.36374607,
         1.36374607, 1.36374607],
        [1.37748519, 1.36374607, 1.21843483, ..., 1.36374607,
         1.36374607, 1.36374607],
        ...,
        [1.36374607, 1.36374607, 1.36374607, ..., 1.36374607,
         1.36374607, 1.36374607],
        [1.36374607, 1.36374607, 1.36374607, ..., 1.36374607,
         1.36374607, 1.36374607],
        [1.36374607, 1.36374607, 1.36374607, ..., 1.36374607,
         1.36374607, 1.36374607]]])

In [201]:
test3_transpose_alt()

Размер тензора - (1, 65, 65)


array([[[ 0.70539871,  0.70539871,  0.70539871, ...,  0.70539871,
          0.70539871,  0.70539871],
        [ 0.70539871,  5.67743268, -2.43072781, ..., -1.81048021,
         -2.11364564,  0.70539871],
        [ 0.70539871, -8.59915242,  1.27254191, ..., -1.94778881,
          0.56423411,  0.70539871],
        ...,
        [ 0.70539871,  5.84268394,  0.99975601, ..., -3.00894746,
         -4.03442893,  0.70539871],
        [ 0.70539871,  6.89380088, -0.54163537, ...,  4.94321456,
          6.06931272,  0.70539871],
        [ 0.70539871,  0.70539871,  0.70539871, ...,  0.70539871,
          0.70539871,  0.70539871]]])

In [202]:
test4_transpose_alt()

Размер тензора - (1, 68, 68)


array([[[0.19850769, 0.89235463, 0.62025114, ..., 0.80637732,
         0.80637732, 0.80637732],
        [0.34350338, 1.33945277, 0.49456974, ..., 0.80637732,
         0.80637732, 0.80637732],
        [0.80485666, 0.84495962, 1.34251859, ..., 0.80637732,
         0.80637732, 0.80637732],
        ...,
        [0.80637732, 0.80637732, 0.80637732, ..., 0.80637732,
         0.80637732, 0.80637732],
        [0.80637732, 0.80637732, 0.80637732, ..., 0.80637732,
         0.80637732, 0.80637732],
        [0.80637732, 0.80637732, 0.80637732, ..., 0.80637732,
         0.80637732, 0.80637732]]])